# Generated by Django 5.0.7 on 2024-07-15 13:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Deletado"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="Deletado às"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado às"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado às"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Código do ativo"
                    ),
                ),
            ],
            options={"verbose_name": "Ativo", "verbose_name_plural": "Ativos",},
        ),
        migrations.CreateModel(
            name="SearchConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Deletado"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="Deletado às"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado às"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado às"),
                ),
                (
                    "all_stocks",
                    models.BooleanField(default=False, verbose_name="Todos os ativos"),
                ),
                (
                    "interval",
                    models.DurationField(
                        default=datetime.timedelta(seconds=300),
                        verbose_name="Intervalo entre buscas (minutos)",
                    ),
                ),
                (
                    "stocks",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="buscas",
                        to="b3.stock",
                        verbose_name="Ativos Monitorados",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Busca",
                "verbose_name_plural": "Configurações de Buscas",
            },
        ),
        migrations.CreateModel(
            name="StockPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Deletado"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="Deletado às"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado às"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado às"),
                ),
                (
                    "search",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="b3.searchconfig",
                        verbose_name="Configuração de Busca",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="b3.stock",
                        verbose_name="Preço do Ativo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Preço do Ativo",
                "verbose_name_plural": "Preços dos Ativos",
            },
        ),
    ]
