# Generated by Django 5.0.7 on 2024-07-19 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_celery_beat", "0018_improve_crontab_helptext"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Deletado"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="Deletado às"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado às"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado às"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Código do ativo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ativo",
                "verbose_name_plural": "Ativos",
            },
        ),
        migrations.CreateModel(
            name="Search",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Deletado"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="Deletado às"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado às"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado às"),
                ),
                (
                    "price_tunnel",
                    models.CharField(
                        choices=[
                            ("SUPERIOR", "SUPERIOR"),
                            ("NEGOCIOS", "NEGOCIOS"),
                            ("INFERIOR", "INFERIOR"),
                        ],
                        default="LAST_TRADED_PRICE",
                        max_length=20,
                        verbose_name="Túnel de Preço",
                    ),
                ),
                (
                    "interval",
                    models.IntegerField(
                        default=5, verbose_name="Intervalo entre buscas (minutos)"
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_celery_beat.periodictask",
                    ),
                ),
                (
                    "stocks",
                    models.ManyToManyField(
                        blank=True,
                        related_name="buscas",
                        to="b3.stock",
                        verbose_name="Ativos Monitorados",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Busca",
                "verbose_name_plural": "Configurações de Buscas",
            },
        ),
        migrations.CreateModel(
            name="StockPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Deletado"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="Deletado às"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado às"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado às"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Preço do Ativo"
                    ),
                ),
                (
                    "search",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="b3.search",
                        verbose_name="Configuração de Busca",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="b3.stock",
                        verbose_name="Preço do Ativo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Preço do Ativo",
                "verbose_name_plural": "Preços dos Ativos",
            },
        ),
    ]
