# Generated by Django 5.0.7 on 2024-07-18 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("b3", "0002_auto_20240718_1937"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SearchRequest",
        ),
    ]
